platform :ios, '11.0'
use_frameworks!

target 'GitHubSearch' do
    pod 'SnapKit', '~> 4.0.0'
    pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'
	pod 'Alamofire', '~> 4.7'
	pod 'AlamofireImage', '~> 3.3'
	pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
	
	target 'GitHubSearchTests' do
		inherit! :complete
	end
	target 'GitHubSearchViewControllersTests' do
		inherit! :complete
	end
	target 'GitHubSearchUserDetailsTests' do
		inherit! :complete
	end
end
